version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "3030:3030"
    depends_on:
      - backend
    env_file: ./frontend/.env

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - COUNTRIES_API=${COUNTRIES_API}
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:13
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    volumes:
      - postgres-data:/var/lib/postgresql/data

    # I added this healthcheck cos i noticed the backend commincates with the db before the database starts running,
    # so this helps to make the backend restart the connection until the database is ready. using the "pg_isReady" tag
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
