name: Vacation App CI/CD pipeline
on:
  push:
    branches: [main, dev, staging]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yaml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vacation-app-frontend:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacations-frontend:$SHORT_SHA frontend/
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vacation-app-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vacation-app-frontend:$SHORT_SHA
